CON-440 - updated beta frontpage redirect url
Financial-Times/n-myft-ui pull request #428
Opened 2020-10-21 13:34 UTC by gyss

* renamed frontPageAlpha flag to betaFrontPageOptIn
* updated beta frontpage redirect url

Meta: 
(Jira)[https://financialtimes.atlassian.net/browse/CON-439] + (Jira)[https://financialtimes.atlassian.net/browse/CON-440]

2020-10-21 14:53 UTC, kavanagh requested changes
Looks good. Just change - flag names 😃

2020-10-21 14:53 UTC, kavanagh commented on myft/ui/navigationBetaTest.js
> +		((opts.flags.get && opts.flags.get('betaFrontPageOptIn')) || opts.flags.betaFrontPageOptIn)
I think I want to change my mind about flag names.

I think this one should be `betaHomePage` and the kill switch should be `betaHomePageKillSwitch`

Based on a discussion I had with Anna and the data team yesterday, in the future I think there will need to be a third flag for the Opt-in button. In that case it should be something like `betaHomePageOptInJourney` so I'd rather avoid the Opt-in part of the name at the moment.

2020-10-21 15:29 UTC, kavanagh approved these changes

2020-10-22 08:25 UTC, umbobabo approved these changes
Approved but with one clarification needed

2020-10-22 08:25 UTC, umbobabo commented on myft/ui/navigationBetaTest.js
> +		((opts.flags.get && opts.flags.get('betaHomePage')) || opts.flags.betaHomePage)
I thought we decided to go with `betaFrontPageOptIn`, didn't we? This is fine but I just need to know cause it's affect [my PR](https://github.com/Financial-Times/next-discovery-pages/pull/50)

2020-10-22 09:09 UTC, gyss commented on myft/ui/navigationBetaTest.js
> +		((opts.flags.get && opts.flags.get('betaHomePage')) || opts.flags.betaHomePage)
I'm sorry, I thought you read this slack message yesterday: 

https://financialtimes.slack.com/archives/C010BC61NDS/p1603293205169100?thread_ts=1603291188.165000&cid=C010BC61NDS

Luke told me we'll probably that OptIn env var in the future: https://github.com/Financial-Times/n-myft-ui/pull/428

2020-10-22 09:20 UTC, gyss commented on myft/ui/navigationBetaTest.js
> +		((opts.flags.get && opts.flags.get('betaHomePage')) || opts.flags.betaHomePage)
see above comment from Luke

2020-10-23 08:55 UTC, merged