fix: CPORM-16 - Npm migration
Financial-Times/n-myft-ui pull request #494
Opened 2022-05-13 15:20 UTC by JSRedondo

Migrate from bower to npm.
Install components as peer dependencies with financial-times scope and fix references.

2022-05-13 15:28 UTC, debugwand requested changes

2022-05-13 15:28 UTC, debugwand commented on package.json
> +    "@financial-times/n-notification": "^8.2.2",
these have bumped by a major version from the version in bower.json, so we don't know if there will be a breaking change. we also don't actually need to move the origami components from bower.json as part of this work

2022-05-16 08:20 UTC, JSRedondo commented on package.json
> +    "@financial-times/n-notification": "^8.2.2",
We can review the status of the task after your PR will be approved, just to make sure everything is ok.

2022-05-16 13:53 UTC, closed without merging

2022-05-16 13:54 UTC, JSRedondo commented
Incompatible with current changes