UG-936 Display notification after unsaving article
Financial-Times/n-myft-ui pull request #521
Opened 2022-08-08 14:07 UTC by Shamarni96

### Description
After a user unsaves an article, a notification is displayed. See [designs](https://www.figma.com/file/09mlE9M0XVG5fIZy99tls2/(Final)-Professor-Engagement?node-id=758%3A7466) (Frame 245 & Frame 249).

### Ticket
https://financialtimes.atlassian.net/browse/UG-936

### How To Test
1) clone `next-article` and run `npm install build` 
2) Make sure you’re logged in on Vault and run `next-article` with `npm start`
3) Switch on the manageArticleLists flag on [Toggler](https://toggler.ft.com/#manageArticleLists)
4) visit https://local.ft.com:5050/
5) Go to any article and click the “save” button in the shareNav menu. The save article modal should appear next to the ShaveNav menu.
6) click the save button again to unsave the article. the unsave article notification should show with the text `"Removed from saved articles in myFT"` and should disappear after 5 seconds.
7) The unsaved notification should only show when the `manageArticleLists` flag is switched on. To ensure that this works, switch the `manageArticleLists` flag off and repeat steps 4 - 6

2022-08-09 08:44 UTC, jamesnicholls requested changes
The code works perfectly, as described. I think the only blocker is that the font used in the notification doesn't look right. In the design it's Metric. Also, can you check the message in the notification with Dilyana and Ajai?

Apart from that, I have a couple of questions and suggestions.

2022-08-09 08:44 UTC, jamesnicholls commented on myft/ui/lists.js
> +		<p role="alert">Removed from <a href="https://www.ft.com/myft/saved-articles">saved articles</a> in myFT only.</p>
**chore:** Can you check the wording with Dilyana and Ajai? I think Dilyana wanted to change it.

2022-08-09 08:44 UTC, jamesnicholls commented on myft/main.scss
> +			font-size: 16px;
**nitpick:** I think you'll need to specify the font-family here as well. In the designs, the font used is Metric, but I don't think the notification is using that font locally.

2022-08-09 08:44 UTC, jamesnicholls commented on myft/main.scss
> +			position: absolute;
**suggestion (non-blocking):** You could move the styles shared between the horizontal and vertical versions of the notification into a common rule set.

2022-08-09 08:44 UTC, jamesnicholls commented on myft/main.scss
> +				margin: auto;
**question:** What is this rule for?

2022-08-09 08:44 UTC, jamesnicholls commented on myft/ui/lists.js
> +		<p role="alert">Removed from <a href="https://www.ft.com/myft/saved-articles">saved articles</a> in myFT only.</p>
**praise:** Nice work thinking about accessibility here. The notification is announced perfectly in VoiceOver.

2022-08-09 14:23 UTC, Shamarni96 commented on myft/main.scss
> +				margin: auto;
I forgot to remove this once I figured out I didn't need it but I added it to try to center the text in the notification. I have now removed it 👍

2022-08-09 14:32 UTC, Shamarni96 commented on myft/ui/notification.js
> +let isShowing = false;
yep you are right. I have deleted this file 👍

2022-08-09 16:09 UTC, jamesnicholls approved these changes
Looks good, nice work.

2022-08-11 08:17 UTC, fenglish commented on myft/main.scss
> +@include oTypography();
Would this cause the same issue in the n-myft-ui's consumer apps as [this](https://github.com/Financial-Times/n-myft-dropdown/pull/8)?
I'm not 100% sure this is ok or not. Please talk to @meel-io.

2022-08-11 09:54 UTC, Shamarni96 commented on myft/main.scss
> +@include oTypography();
I have removed this line of code 👍

2022-08-11 11:14 UTC, fenglish approved these changes
@Shamarni96 Thank you for your change. Please keep eye on the consumer apps (not only next-article) when you release changes.

2022-08-11 11:25 UTC, merged