UG-959: Add showMessageOverlay function to manageArticleLists component
Financial-Times/n-myft-ui pull request #524
Opened 2022-08-15 14:46 UTC by meel-io

### Description

Adds the showMessageOverlay that displays the fake door message for this smoke test
Adds the MessageElement component that includes the markup of the message and expects a clickHandler and attaches it to its button
Adds logic in the createList callback to close the createListOverlay and show the messageOverlay if the Public toggle is checked
The showMessageOverlay passes the clickHandler to the MessageElement with logic to close the messageOverlay and restore the createListOverlay after clicking on "Continue"

2022-08-16 13:18 UTC, jamesnicholls requested changes
Notification works great. I don't think it was introduced in this PR, but I'm seeing this visual bug on screen sizes (~394px wide):

<img width="2032" alt="Screenshot 2022-08-16 at 12 53 51" src="https://user-images.githubusercontent.com/1705375/184889325-271c0ac7-2cea-497a-8fd5-32286bac5406.png">

2022-08-16 16:15 UTC, meel-io commented on myft/ui/save-article-to-list-variant.js
> +	<div class="myft-ui-create-list-variant-message-content">
Thanks for keeping an eye on accessibility. Setting it to `alert` didn't work well with the created list announcement. Using the `aria-live=polite` does the trick: It announces the created list and then it reads the content of the fake door message

2022-08-16 16:16 UTC, meel-io commented on myft/ui/save-article-to-list-variant.js
> +			if (inputIsShareable.checked) {
Good point 👍 I've added this change

2022-08-17 08:42 UTC, jamesnicholls commented on myft/ui/save-article-to-list-variant.js
> +	<div class="myft-ui-create-list-variant-message-content">
This works great. In fact, the whole component is really nice to use with a screen reader.

2022-08-17 08:45 UTC, jamesnicholls approved these changes
The notification works great. I'm still getting the visual bug described above, but happy to address this in a different PR.

2022-08-17 10:21 UTC, merged