UG-1127 Public lists post test cleanup
Financial-Times/n-myft-ui pull request #567
Opened 2023-02-20 15:59 UTC by Shamarni96

### Description
As a result of the public/private lists test being successful, the public/private toggle feature is now ready to be shipped to all users. This PR involves removing any config that was created for the test.

### Ticket
https://financialtimes.atlassian.net/browse/UG-1127

### How to test
1. checkout this branch locally
2. run `make install` and then run `npm link`
3. Clone `next-article` , run `npm install` and then run `npm link @financial-times/n-myft-ui`
4. Run `npm run watch` on `next-article`
5. Make sure you’re logged in on Vault and run next-article in a new terminal with `npm start`
6. Go to any article and click on “Save”. The modal should appear next to the ShaveNav menu.
7. click "add to a new list" and you should see the public/private toggle
8. click the toggle to ensure it switches between public and private
9. save the article to a new list and visit https://local.ft.com:5050/myft/lists/ to ensure that the list has been saved successfully.

2023-02-21 11:05 UTC, Shamarni96 commented on myft/ui/lists.js
> -		...config
ah okay I see, I forgot that this could affect other pages that the modal is being used on. will try to fix this issue now 👍

2023-02-21 11:06 UTC, Shamarni96 commented on myft/ui/save-article-to-list-variant.js
> -function checkScrollToAdd () {
working on it 🫡

2023-02-24 12:09 UTC, Shamarni96 commented on myft/ui/lists.js
> -		...config
I have reverted these changes 👍

2023-02-28 11:27 UTC, jamesnicholls requested changes
Saving an article to a new list from the [saved articles page](https://www.ft.com/myft/saved-articles/) doesn't work for me (the article doesn't get added to the list), but the new list is set correctly to public/private, so I don't think this is due to your PR. We should create another ticket to fix the bug though.

Apart from that, I only have one minor nitpick about indentation. The code works perfectly though.

2023-02-28 15:03 UTC, Shamarni96 commented on myft/ui/save-article-to-list-variant.js
> +			</div>
fixed 👍

2023-02-28 15:49 UTC, jamesnicholls approved these changes

2023-02-28 16:15 UTC, gyss approved these changes

2023-03-02 10:34 UTC, merged