init commit
Financial-Times/n-myft-ui pull request #588
Opened 2023-08-08 13:03 UTC by asugar13

2023-08-10 08:48 UTC, asugar13 commented on components/instant-alerts-onboarding/instant-alerts-onboarding.html
> +						<input type="checkbox" name="receive-instant-alerts" value="receive-instant-alerts">
**Note**: a11y tests are not passing because of this checkbox. I need to figure out a way to submit the form by clicking on the checkbox.

2023-08-10 08:49 UTC, asugar13 commented on components/instant-alerts-onboarding/main.scss
> +	// font-size: 14px;
**Note**: I left the `font-size` commented out to highlight the fact that there are a few design inconsistencies in the font choices.

2023-08-10 13:00 UTC, GlynnPhillips commented on components/instant-alerts-onboarding/instant-alerts-onboarding.html
> +						<input type="checkbox" name="receive-instant-alerts" value="receive-instant-alerts">
**Suggestion:** A possible suggestion here (I am still thinking if its the best way) would be to have hidden submit button within the form. Then when the user clicks on the checkbox we can submit the form via JS instead of using the submit button.

2023-08-10 13:01 UTC, GlynnPhillips commented on components/instant-alerts-onboarding/main.scss
> +	// font-size: 14px;
Can you provide more details about what you mean by this?

2023-08-10 13:03 UTC, GlynnPhillips commented on components/instant-alerts-onboarding/instant-alerts-onboarding.html
> +	<div class="n-myft-ui__instant-alerts-onboarding">
**Suggestion:** I wonder if our naming could be more generic / future proofed? Maybe something like `n-myft-ui__follow-menu` or `n-myft-ui__follow-manage` so that if we want to add other options into here we can?

2023-08-10 13:06 UTC, GlynnPhillips commented on components/instant-alerts-onboarding/main.scss
> +.n-myft-ui__instant-alerts-onboarding__checkbox {
**Comment:** I am not sure if we should achieve this in this way. However to be sure I would like to run the demos and play around with it. I am in the middle of doing something in n-myft-ui so I need to find a good stopping point to do that

2023-08-10 14:11 UTC, asugar13 commented on components/instant-alerts-onboarding/instant-alerts-onboarding.html
> +	<div class="n-myft-ui__instant-alerts-onboarding">
will go with `n-myft-ui__preference-modal`

2023-08-10 16:08 UTC, asugar13 commented on components/instant-alerts-onboarding/main.scss
> +.n-myft-ui__instant-alerts-onboarding__checkbox {
good call. moving the relative positioning to `n-myft-ui__preferences-modal__content`

2023-08-10 16:11 UTC, asugar13 commented on components/instant-alerts-onboarding/instant-alerts-onboarding.html
> +						<input type="checkbox" name="receive-instant-alerts" value="receive-instant-alerts">
This is a good suggestion. However, since removing the form passes linting, that's what I've done for now. The main reason is that I think implementing this functionality is part of a separate task to make the API call to change the user's preferences. However, let me know: I could add a simple onClick listener without much functionality to it.

2023-08-11 13:21 UTC, GlynnPhillips commented on components/jsx/instant-alerts-preferences/instant-alerts-preferences.jsx
> +	}
**Comment:** Yeah probably not needed but I still think its worth having as its a simply bit of protection just incase someone loads this component without checking first

2023-08-11 13:24 UTC, asugar13 commented on components/jsx/instant-alerts-preferences/instant-alerts-preferences.jsx
> +	const formattedCurrentPreferences = currentPreferences.join(', ')
sounds good. In this case I added functionality for the fields to be populated dynamically. However there are no designs for the case where there are no alerts set up for the user.

2023-08-11 13:26 UTC, GlynnPhillips commented on components/jsx/instant-alerts-preferences/main.scss
> +}
**Question:** Do we need this extra child element within the button? If we are only applying font styles then they can be applied directly to the button

2023-08-11 13:28 UTC, GlynnPhillips commented on components/jsx/instant-alerts-preferences/main.scss
> +	justify-content: center;
**Comment:** I don't think we need this to be flex, especially if we remove the child element. The horizontal centering can be achieved with `text-align: center` and the vertical centering can be achieved by creating the height with equal padding

2023-08-11 13:31 UTC, GlynnPhillips commented on components/jsx/instant-alerts-preferences/instant-alerts-preferences.jsx
> +				<button class="n-myft-ui__preferences-modal__remove-button"><p class="n-myft-ui__preferences-modal__remove-button__text">Remove from myFT</p></button>
**Change request:** Buttons can only contain inline elements and `p` is a block level element.

Also see my comment about the css because I think this child element is not required anyway

2023-08-11 13:32 UTC, GlynnPhillips commented on components/jsx/instant-alerts-preferences/main.scss
> +	font-size: 14px;
**Comment:** Should we use an origami mixin here to set the font size?

2023-08-11 13:33 UTC, GlynnPhillips commented on components/instant-alerts-preferences/instant-alerts-preferences.html
Do we need a handlebars version?

2023-08-11 13:38 UTC, GlynnPhillips commented on components/jsx/instant-alerts-preferences/instant-alerts-preferences.jsx
> +	const formattedCurrentPreferences = currentPreferences.join(', ')
Yeah I just want to be careful to avoid big bang work. The ticket you are working on calls out that its not inscope to create any of the functionality within the modal. There is already a ticket PT-236 for doing the preference display work

2023-08-11 13:39 UTC, GlynnPhillips commented on components/jsx/instant-alerts-preferences/instant-alerts-preferences.jsx
As we have called the classnames for this to be preference modal should we make the file names match?

2023-08-11 13:42 UTC, asugar13 commented on components/instant-alerts-preferences/instant-alerts-preferences.html
whoops! forgot to remove it

2023-08-11 14:10 UTC, asugar13 commented on components/jsx/instant-alerts-preferences/instant-alerts-preferences.jsx
I can do that but I felt like one of the reasons to change the classNames was that the original name was a bit wordy. I think the file name gives a bit of a more descriptive explanation of what the component is there for.

2023-08-11 14:12 UTC, GlynnPhillips commented on components/jsx/instant-alerts-preferences/instant-alerts-preferences.jsx
> name was a bit wordy

That wasn't a concern for me, I have no issue with wordy names that are descriptive. My concern here is you have a filename that makes it sound very specific but then then code is aimed to make it sound generic. We should pick 1 or the other

2023-08-11 14:15 UTC, asugar13 commented on components/jsx/instant-alerts-preferences/instant-alerts-preferences.jsx
the original name was `instant-alerts-onboarding` (https://github.com/Financial-Times/n-myft-ui/pull/588#discussion_r1290094114) I will go with `instant-alerts-preferences` instead

2023-08-11 14:23 UTC, GlynnPhillips commented on components/jsx/instant-alerts-preferences/instant-alerts-preferences.jsx
> instant-alerts-preferences

I personally think that this is confusing because we have other components that already exist on the site to deliver "instant alerts preferences"

>  I think the file name gives a bit of a more descriptive explanation of what the component is there for


I think the name we choice (preference modal ) is descriptive without being too specific. There is no point in our code being generic so the component can be extended if the filename is then overly specific.

Whatever choice you go with I would like to see the code and the file name reflect each other.

2023-08-11 14:58 UTC, asugar13 commented on components/jsx/instant-alerts-preferences/main.scss
> +	justify-content: center;
I believe this was needed when there was a <p> inside the <button> but it's no longer needed:
```    
display: flex;
align-items: center;
justify-content: center;
```

2023-08-14 10:18 UTC, GlynnPhillips requested changes
A couple of minor improvements but its looking good

2023-08-14 10:18 UTC, GlynnPhillips commented on components/jsx/preferences-modal/main.scss
> +.n-myft-ui__preferences-modal__remove-button:hover {
**Change request:** Here I think we need to account for `focus` state as well to allow for keyboard navigation

```suggestion
.n-myft-ui__preferences-modal__remove-button:hover,
.n-myft-ui__preferences-modal__remove-button:focus {
```

2023-08-14 10:18 UTC, GlynnPhillips commented on components/jsx/preferences-modal/preferences-modal.jsx
> +		</div>
**Change request:** This is now jsx so all the `class` attributes in here need to be `className`

2023-08-14 10:18 UTC, GlynnPhillips commented on components/jsx/preferences-modal/preferences-modal.jsx
> +							<input type="checkbox" name="receive-instant-alerts" value="receive-instant-alerts"></input>
**Nitpick:** `input` can be self closing here if you want 

```suggestion
							<input type="checkbox" name="receive-instant-alerts" value="receive-instant-alerts" />
```

2023-08-14 10:18 UTC, GlynnPhillips commented on components/jsx/preferences-modal/preferences-modal.jsx
> +				<p class="n-myft-ui__preferences-modal__manage-preferences">Manage your preferences <a href="/myft/alerts">here</a></p>
**Comment/Change request:** Maybe this can't be a change request until we speak to Design or Product but we should avoid "here" or "click here" type of links as they are bad for accessibility. For example if a user is use assistive tech to navigate via links in the page they wont know what "here" is as they wont have the "manage your preference" context.

I would suggest we do something like the below 
```suggestion
				<a href="/myft/alerts" className="n-myft-ui__preferences-modal__manage-preferences">Manage your preferences </a>
```

2023-08-14 10:27 UTC, asugar13 commented on components/jsx/preferences-modal/preferences-modal.jsx
> +							<input type="checkbox" name="receive-instant-alerts" value="receive-instant-alerts"></input>
true. it was self-closing at some point in the review. Can't remember why I added the closing tag.

2023-08-14 10:41 UTC, asugar13 commented on components/jsx/preferences-modal/preferences-modal.jsx
> +				<p class="n-myft-ui__preferences-modal__manage-preferences">Manage your preferences <a href="/myft/alerts">here</a></p>
Instead of committing your suggestion, should I add it to this ticket to discuss with designer once he's back from time off? : https://financialtimes.atlassian.net/browse/PT-249

2023-08-14 13:33 UTC, asugar13 commented on components/jsx/preferences-modal/preferences-modal.jsx
> +				<p class="n-myft-ui__preferences-modal__manage-preferences">Manage your preferences <a href="/myft/alerts">here</a></p>
I've gone ahead and made that change and updated the ticket so we can run it by Mark when he's back.

2023-08-14 14:29 UTC, GlynnPhillips approved these changes

2023-08-16 10:39 UTC, gyss commented
Looks good @asugar13 ! just one thing, on mobile, looks like the component is taking more width than the grid container. Is this being considered?

![Screenshot 2023-08-16 at 11 39 01](https://github.com/Financial-Times/n-myft-ui/assets/2237167/756b35bd-b6da-4c4c-a128-0caca5f219d0)

2023-08-16 11:11 UTC, metart43 requested changes

2023-08-16 11:11 UTC, metart43 commented on components/jsx/preferences-modal/preferences-modal.jsx
> +							<input type="checkbox" name="receive-instant-alerts" value="receive-instant-alerts"/>
I might be wrong but I reckon the association between `<label>` and `<input>` is done through the `id` prop.

So, you just simply need to add `id` property to the `<input>` checkbox

```jsx
<input id="receive-instant-alerts" type="checkbox" name="receive-instant-alerts" value="receive-instant-alerts" />
```

2023-08-16 11:11 UTC, metart43 commented on components/jsx/preferences-modal/preferences-modal.jsx
> +				<a className="n-myft-ui__preferences-modal__text">Manage your preferences here</a>
Sorry, I am not sure why there is an `<a>` tag with a `href` property.


Without a valid `href`, this element could be confusing to screen readers and other assistive technologies. If it's meant to be interactive (like a button), it's better to use a `<button>` element or provide appropriate roles and ARIA attributes.

2023-08-16 12:16 UTC, asugar13 commented on components/jsx/preferences-modal/preferences-modal.jsx
> +							<input type="checkbox" name="receive-instant-alerts" value="receive-instant-alerts"/>
Sounds good, I'll add the `id`. It seems like it's a good accessibility practice

2023-08-16 12:17 UTC, asugar13 commented on components/jsx/preferences-modal/preferences-modal.jsx
> +				<a className="n-myft-ui__preferences-modal__text">Manage your preferences here</a>
Good spot! I think the href went away in a series of rebases I did.

2023-08-16 12:52 UTC, GlynnPhillips commented on components/jsx/preferences-modal/preferences-modal.jsx
> +							<input type="checkbox" name="receive-instant-alerts" value="receive-instant-alerts"/>
Just for future reference, if you have an implicit label & input relationship (eg. the label is wrapping the input) then you don't need the `for` & `id` relationship (explicit relationship) - however doing both is also not a problem

2023-08-16 12:54 UTC, GlynnPhillips commented on components/jsx/preferences-modal/preferences-modal.jsx
> +							<input type="checkbox" name="receive-instant-alerts" value="receive-instant-alerts"/>
Explicit relationships are better for accessibility but they still don't work perfectly if combined with an implicit relationship. However our styling via forms does rely on an implicit relationship so I don't think theres a way around that

2023-08-16 12:58 UTC, asugar13 reviewed
@gyss , this is how the component looks like on mobile when being imported into other apps such as `next-article`: 
<img width="485" alt="Screenshot 2023-08-16 at 13 53 12" src="https://github.com/Financial-Times/n-myft-ui/assets/10453619/d72c2b6c-33be-465c-ac4b-1cdd69c6ec1c">

2023-08-16 13:04 UTC, gyss approved these changes

2023-08-16 14:04 UTC, metart43 approved these changes

2023-08-17 08:23 UTC, merged